FROM python:3.9

LABEL maintainer "Artem Baidin <ufo3939@gmail.com>"

WORKDIR /app

USER 0
ADD app .
RUN chown -R 1001:0 /app && \
    chmod +x /app/run.sh

RUN pip install -r /app/requirements.txt 
USER 1001

EXPOSE 9119

ENTRYPOINT ["/app/run.sh"]
